name: Docker Build and Push

on:
  push:
    branches:
      - main  # atau branch yang ingin kamu gunakan untuk build otomatis
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build and push Docker image
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: rayyanazzuhri/sisabsi:latest
